---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starterapp-python
spec:
  selector:
    matchLabels:
      app: starterapp-python
  template:
    metadata:
      labels:
        app: starterapp-python
    spec:
      containers:
      - name: starterapp-python
        image: quay.io/nexus6/starter-app-python:latest
